language: c

matrix:
    include:
        - os: linux
          dist: trusty
          addons:
            apt:
              packages:
              - autopoint
              - automake
              - autoconf
              - intltool
              - libc6-dev-i386
              - libc6-dev
              - yasm
              - perl
              - wget
              - g++-multilib
              - zip
              - libglib2.0-bin
              - libgtk-3.0
              - libpulse0
              - libstdc++6
          sudo: required
        - os: osx
          osx_image: xcode11.3

git:
  submodules: false

script:
    - ./travis/build.sh

after_success:
    - ./travis/upload.sh

notifications:
    irc:
        channels:
            - "chat.freenode.net#deadbeefplayer"
        on_success: always
        on_failure: always
        template:
            - "%{branch} - %{commit} : %{author} : %{message}"
            - "Commit message: %{commit_subject}"
            - "Diff: %{compare_url}"
            - "Build details: %{build_url}"
