language: c

git:
  submodules: false

os:
    - linux

script:
    - ./travis/build.sh
    - ./travis/upload.sh

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y -qq autopoint automake autoconf intltool libc6-dev-i386 libc6-dev yasm perl wget g++-multilib zip libglib2.0-bin libgtk-3.0 libpulse0

notifications:
    irc:
        channels:
            - "chat.freenode.net#deadbeefplayer"
        on_success: always
        on_failure: always
        template:
            - "%{branch} - %{commit} : %{author} : %{message}"
            - "Commit message: %{commit_subject}"
            - "Diff: %{compare_url}"
            - "Build details: %{build_url}"
